try {
    console.log("Lỗi nè")
} catch (error) {
    //Xử lý lỗi trong đây!
}