try {
    console.log("Error")
} catch (error) {
    //Xử lý lỗi
}